[workspace]
members = [
	"client/cli",
	"client/consensus/common",
	"client/consensus/relay-chain",
	"client/consensus/nimbus",
	"client/network",
	"client/pov-recovery",
	"client/service",
	"pallets/author-inherent",
	"pallets/author-slot-filter",
	"pallets/aura-style-filter",
	"pallets/dmp-queue",
	"pallets/parachain-system",
	"pallets/account-set",
	"pallets/xcm",
	"pallets/xcmp-queue",
	"primitives/core",
	"primitives/nimbus",
	"primitives/parachain-inherent",
	"primitives/utility",
	"polkadot-parachains/",
	"polkadot-parachains/pallets/parachain-info",
	"polkadot-parachains/pallets/ping",
	"polkadot-parachains/nimbus-runtime",
	"polkadot-parachains/rococo-runtime",
	"polkadot-parachains/shell-runtime",
	"test/runtime",
	"test/runtime-upgrade",
	"test/client",
	"test/service",
	"test/relay-sproof-builder",
	"test/relay-validation-worker-provider",
]

[profile.release]
panic = "unwind"
